version: '3.8'

services:
  # MySQL 資料庫
  db:
    image: mysql:8.0
    container_name: stream-monitor-mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-facemotion}
      - MYSQL_USER=${MYSQL_USER:-facemotion}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-facemotion123}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root123}
      - TZ=Asia/Taipei
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - monitor-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-root123}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "3306:3306"

  # API服務
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stream-monitor-api
    restart: unless-stopped
    ports:
      - "8282:8282"
    volumes:
      - ./config:/app/config
      - ./screenshots:/app/screenshots
      - ./logs:/app/logs
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - DB_HOST=db
      - MYSQL_DATABASE=${MYSQL_DATABASE:-facemotion}
      - MYSQL_USERNAME=${MYSQL_USER:-facemotion}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-facemotion123}
      - SESSION_SECRET=${SESSION_SECRET:-your-secret-key-change-this}
      - LOG_LEVEL=INFO
      - TZ=Asia/Taipei
    networks:
      - monitor-network
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8282/api/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 監控服務 (處理影像串流和檢測)
  monitor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stream-monitor-service
    restart: unless-stopped
    command: python start_system.py
    volumes:
      - ./config:/app/config
      - ./screenshots:/app/screenshots
      - ./logs:/app/logs
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - DB_HOST=db
      - MYSQL_DATABASE=${MYSQL_DATABASE:-facemotion}
      - MYSQL_USERNAME=${MYSQL_USER:-facemotion}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-facemotion123}
      - LOG_LEVEL=INFO
      - TZ=Asia/Taipei
      - AUTO_START=true
    networks:
      - monitor-network
    depends_on:
      - api
      - db
    # 如需使用GPU
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

  # Nginx反向代理 (可選)
  nginx:
    image: nginx:alpine
    container_name: stream-monitor-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./screenshots:/app/screenshots:ro
    networks:
      - monitor-network
    depends_on:
      - api
    # 可選配置

networks:
  monitor-network:
    driver: bridge

volumes:
  screenshots:
  logs:
  data:
  models:
  mysql_data:
